{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Event invocations have to be prefixed by \"emit\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fc/fc4b096c41786d087dbc40bec1601efba5dca2d7_YJECC.sol:364:1:\n    |\n364 | Blacklisted(_addr);\r\n    | ^^^^^^^^^^^^^^^^^^\n\nError: Event invocations have to be prefixed by \"emit\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fc/fc4b096c41786d087dbc40bec1601efba5dca2d7_YJECC.sol:374:1:\n    |\n374 | DeleteFromBlacklist(_addr);\r\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Event invocations have to be prefixed by \"emit\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fc/fc4b096c41786d087dbc40bec1601efba5dca2d7_YJECC.sol:517:1:\n    |\n517 | RejectedPaymentFromBlacklistedAddr(msg.sender, recipient, amount);\r\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Event invocations have to be prefixed by \"emit\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fc/fc4b096c41786d087dbc40bec1601efba5dca2d7_YJECC.sol:525:1:\n    |\n525 | RejectedPaymentToBlacklistedAddr(msg.sender, recipient, amount);\r\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n", "results": {}}
