{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Multiple SPDX license identifiers found in source file. Use \"AND\" or \"OR\" to combine multiple licenses. Please see https://spdx.org for more information.\n--> /Users/giacomoibba/Desktop/SmarthER/mainnet/fe/feb0b0af20d819804e93f3e8e2dc7782cae800c2_TSUWAMONO.sol\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/fe/IERC721A.sol\" not found: File not found. Searched the following locations: \"\".\n --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fe/feb0b0af20d819804e93f3e8e2dc7782cae800c2_TSUWAMONO.sol:7:1:\n  |\n7 | import './IERC721A.sol';\n  | ^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/utils/Context.sol\" not found: File not found. Searched the following locations: \"\".\n    --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fe/feb0b0af20d819804e93f3e8e2dc7782cae800c2_TSUWAMONO.sol:1381:1:\n     |\n1381 | import \"../utils/Context.sol\";\n     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/fe/math/Math.sol\" not found: File not found. Searched the following locations: \"\".\n    --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fe/feb0b0af20d819804e93f3e8e2dc7782cae800c2_TSUWAMONO.sol:1490:1:\n     |\n1490 | import \"./math/Math.sol\";\n     | ^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/lib/openzeppelin-contracts/contracts/utils/Strings.sol\" not found: File not found. Searched the following locations: \"\".\n    --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fe/feb0b0af20d819804e93f3e8e2dc7782cae800c2_TSUWAMONO.sol:2158:1:\n     |\n2158 | import \"../lib/openzeppelin-contracts/contracts/utils/Strings.sol\";\n     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/lib/openzeppelin-contracts/contracts/access/Ownable.sol\" not found: File not found. Searched the following locations: \"\".\n    --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fe/feb0b0af20d819804e93f3e8e2dc7782cae800c2_TSUWAMONO.sol:2159:1:\n     |\n2159 | import \"../lib/openzeppelin-contracts/contracts/access/Ownable.sol\";\n     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/lib/openzeppelin-contracts/contracts/utils/cryptography/MerkleProof.sol\" not found: File not found. Searched the following locations: \"\".\n    --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fe/feb0b0af20d819804e93f3e8e2dc7782cae800c2_TSUWAMONO.sol:2160:1:\n     |\n2160 | import \"../lib/openzeppelin-contracts/contracts/utils/cryptography/MerkleProof.sol\";\n     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/lib/ERC721A/contracts/ERC721A.sol\" not found: File not found. Searched the following locations: \"\".\n    --> /Users/giacomoibba/Desktop/SmarthER/mainnet/fe/feb0b0af20d819804e93f3e8e2dc7782cae800c2_TSUWAMONO.sol:2161:1:\n     |\n2161 | import \"../lib/ERC721A/contracts/ERC721A.sol\";\n     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n", "results": {}}
